### ISSUE TITLE
Immediate KP when injecting or caching this beta kext in Big Sur 11.4

### ISSUE THREAD

**Issue by RV-ABZ** [0xFireWolf/RealtekPCIeCardReader#1]
Whether using the Debug or Release version 0.9.0, I experience a systematic and immediate KP on booting Big Sur 11.4. OS hardly begins to load so there's no log available afterwards.

Test platform is a Dell Latitude E7270 laptop (Skylake) fitted with Realtek RTS525A SD card reader:
Vendor id: 10ec
Device id: 525a
Subsys Ven id: 1028
Subsys id: 06db
Revision: 1

![RTS525a](https://user-images.githubusercontent.com/11544226/122637462-17345980-d0ef-11eb-9421-54ae18fe713e.jpg)
![IMG_4149](https://user-images.githubusercontent.com/11544226/122637464-18fe1d00-d0ef-11eb-8b53-91bcdaf68f28.jpg)
![IMG_4150](https://user-images.githubusercontent.com/11544226/122637466-1a2f4a00-d0ef-11eb-9dae-e2f3c38fd78c.jpg)

**Comment by 0xFireWolf** [comment]
v0.9.1 should fix the issue. Please give a try and see whether the issue still exists.

**Comment by 0xFireWolf** [comment]
Resolved.
