### ISSUE TITLE
Kernel Panic in Ventura

### ISSUE THREAD

**Issue by gujiangjiang** [0xFireWolf/RealtekPCIeCardReader#42]
Kernel Panic in Ventura

panic(cpu 4 caller 0xffffff800c74aee3): Kernel trap at 0xffffff80106c20fb, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x0000000014fca000, CR4: 0x00000000003626e0
RAX: 0x00000000ffffffff, RBX: 0x0000000000000010, RCX: 0x0000000000000000, RDX: 0xffffffffff29fcf4
RSP: 0xffffffffff29fcf0, RBP: 0xffffffffff29fd00, RSI: 0x0000000000000010, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0x0000000000000040, R10: 0xffffffffff29fcf4, R11: 0xffffff86d8d660c8
R12: 0x000000000000fe57, R13: 0xffffff9a085db000, R14: 0x0000000000000030, R15: 0x0000000000000030
RFL: 0x0000000000010202, RIP: 0xffffff80106c20fb, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 1

Panicked task 0xffffff8ba3832218: 215 threads: pid 0: kernel_task
Backtrace (CPU 4), panicked thread: 0xffffff86d8d660c8, Frame : Return Address
0xffffffffff29f6d0 : 0xffffff800c5edf9d 
0xffffffffff29f720 : 0xffffff800c75b786 
0xffffffffff29f760 : 0xffffff800c74aa10 
0xffffffffff29f7b0 : 0xffffff800c588951 
0xffffffffff29f7d0 : 0xffffff800c5ee27d 
0xffffffffff29f8c0 : 0xffffff800c5ed929 
0xffffffffff29f920 : 0xffffff800cde0ecb 
0xffffffffff29fa10 : 0xffffff800c74aee3 
0xffffffffff29fb90 : 0xffffff800c74abd2 
0xffffffffff29fbe0 : 0xffffff800c588951 
0xffffffffff29fc00 : 0xffffff80106c20fb 
0xffffffffff29fd00 : 0xffffff80106c2354 
0xffffffffff29fd40 : 0xffffff80106c496c 
0xffffffffff29fdc0 : 0xffffff80106c46e3 
0xffffffffff29fde0 : 0xffffff80106c9fbf 
0xffffffffff29fe10 : 0xffffff800ccf7c46 
0xffffffffff29fe80 : 0xffffff800ccf79fa 
0xffffffffff29fea0 : 0xffffff800c647b68 
0xffffffffff29fee0 : 0xffffff800c648c1b 
0xffffffffff29ffa0 : 0xffffff800c58819e 
      Kernel Extensions in backtrace:
         science.firewolf.rtsx(0.9.7)[803F199A-AF66-3699-8877-A364AEA81433]@0xffffff80106bc000->0xffffff8010757fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[E2CE416B-59DA-3836-9985-FDC527C5E6C7]@0xffffff800efff000->0xffffff800f02efff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[FB7B8D23-9A09-33DA-89B8-FC81EAA04353]@0xffffff800f132000->0xffffff800f148fff
            dependency: com.apple.iokit.IOUSBHostFamily(1.2)[B4181B36-426B-3C0A-89A5-9C3F3ABAA418]@0xffffff800f3a0000->0xffffff800f414fff

Process name corresponding to current thread (0xffffff86d8d660c8): kernel_task
Boot args: -igfxsklaskbl 

Mac OS version:
22A380

Kernel version:
Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Kernel UUID: BF7C9676-EF23-3E8D-A2E2-25DAC63091B6
roots installed: 0
KernelCache slide: 0x000000000c200000
KernelCache base:  0xffffff800c400000
Kernel slide:      0x000000000c2dc000
Kernel text base:  0xffffff800c4dc000
__HIB  text base: 0xffffff800c300000
System model name: MacBookPro16,4 (Mac-A61BADE1FDAD7B05)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 92268245222801
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000053eadffb0a40
  Sleep   : 0x000053eab57ad180 0x000000011894d93a 0x0000528fc8794ce8
  Wake    : 0x000053eadad55c91 0x0000000117e76446 0x000053eab5e3f980
Compressor Info: 1% of compressed pages limit (OK) and 2% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff806e50e000 - 0xffffffa06e50e000
  . PGZ   : 0xffffff806e50e000 - 0xffffff807150f000
  . VM    : 0xffffff807150f000 - 0xffffff853daa8000
  . RO    : 0xffffff853daa8000 - 0xffffff86d71db000
  . GEN0  : 0xffffff86d71db000 - 0xffffff8ba3774000
  . GEN1  : 0xffffff8ba3774000 - 0xffffff906fd0d000
  . GEN2  : 0xffffff906fd0d000 - 0xffffff953c2a6000
  . GEN3  : 0xffffff953c2a6000 - 0xffffff9a08840000
  . DATA  : 0xffffff9a08840000 - 0xffffffa06e50e000
  Metadata: 0xffffffa08ed1e000 - 0xffffffa0aed1e000
  Bitmaps : 0xffffffa0aed1e000 - 0xffffffa0b7d1e000

last started kext at 90617090911497: @UVCService	1 (addr 0xffffff7fa2659000, size 4096)
last stopped kext at 90882061039496: >!UAudio	500.2 (addr 0xffffff7fa214b000, size 335872)
loaded kexts:
as.acidanthera.BrcmPatchRAM3	2.6.3
me.kishorprins.VoodooInput	1.1.3
com.1Revenger1.RMII2C	1
com.1Revenger1.VoodooRMI	1.3.4
as.acidanthera.voodoo.driver.PS2Keyboard	2.3.0
science.firewolf.rtsx	0.9.7
com.alexandred.VoodooI2C	2.7
ru.joedm.SMCSuperIO	1.3.0
org.coolstar.VoodooGPIO	1.1
as.acidanthera.voodoo.driver.PS2!C	2.3.0
as.lvs1974.RTCMemoryFixup	1.0.7
as.vit9696.SMCProcessor	1.3.0
com.alexandred.VoodooI2CServices	1
as.lvs1974.SMCDellSensors	1.3.0
ru.usrsse2.SMCLightSensor	1.3.0
ru.usrsse2.SMCBatteryManager	1.3.0
as.vit9696.VirtualSMC	1.3.0
as.lvs1974.HibernationFixup	1.4.6
as.lvs1974.AirportBrcmFixup	2.1.6
as.acidanthera.BrcmFirmwareStore	2.6.3
as.acidanthera.BlueToolFixup	2.6.3
science.firewolf.rtsf	1.0.4
as.vit9696.!AALC	1.7.5
com.khronokernel.FeatureUnlock	1.0.9
as.acidanthera.BrightnessKeys	1.0.2
as.vit9696.WhateverGreen	1.6.1
org.acidanthera.NVMeFix	1.1.0
as.vit9696.RestrictEvents	1.0.8
org.acidanthera.driver.CPUFriend	1.2.6
as.vit9696.Lilu	1.6.2
@filesystems.smbfs	5.0
>AudioAUUC	1.70
>!APlatformEnabler	2.7.0d0
>AGPM	131
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
>!AHDA	400.3
>!AGraphicsDevicePolicy	7.1.16
>!AUpstreamUserClient	3.6.9
@AGDCPluginDisplayMetrics	7.1.16
>pmtelemetry	1
@filesystems.nfs	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AHV	1
>!ADiskImages2	198.40.3
>!ASMCLMU	212
>!A!IKBLGraphics	20.0.2
>!A!IPCHPMC	2.0.1
>!ABacklight	180.8
>!A!IKBLGraphicsFramebuffer	20.0.2
>!A!ISlowAdaptiveClocking	4.0.0
>!AMCCSControl	1.16
>!ATopCaseHIDEventDriver	6000.22
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.lifs	1
@filesystems.hfs.kext	627.40.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ASmartBatteryManager	161.0.0
@filesystems.apfs	2142.41.2
@private.KextAudit	1.0
>!AAHCIPort	370
>AirPort.BrcmNIC	1400.1.1
>!AACPIEC	6.1
>!AACPIButtons	6.1
>!ARTC	2.0.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AUserConsent	1
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	403
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@Dont_Steal_Mac_OS_X	7.0.0
@kec.Compression	1
@kec.!AEncryptedArchive	1
>!AHIDKeyboard	231
>DspFuncLib	400.3
@kext.OSvKernDSPLib	530
>!AAudioClockLibs	200.5
>!AGraphicsControl	7.1.16
>usb.IOUSBHostHIDDevice	1.2
@kext.triggers	1.0
>!AHDA!C	400.3
|IOHDA!F	400.3
|IOAudio!F	400.3
@vecLib.kext	1.2.0
>IOHIDPowerSource	1
|IO!BSerialManager	9.0.0
|IO!BPacketLogger	9.0.0
|IO!BHost!CUSBTransport	9.0.0
|IO!BHost!CUARTTransport	9.0.0
|IO!BHost!CTransport	9.0.0
>IO!BHost!CPCIeTransport	9.0.0
|IOAVB!F	1100.24
|CSR!BHost!CUSBTransport	9.0.0
|Broadcom!BHost!CUSBTransport	9.0.0
|Broadcom!B20703USBTransport	9.0.0
>!ARSMChannel	1
|IORSM!F	1
>!AIPAppender	1.0
>!ASMBusPCI	1.0.14d1
>!ABacklightExpert	1.1.0
|IONDRVSupport	597
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
|IOAccelerator!F2	475
@!AGPUWrangler	7.1.16
@!AGraphicsDeviceControl	7.1.16
@plugin.IOgPTPPlugin	1110.13
|IOSlowAdaptiveClocking!F	1.0.0
>driverkit.serial	6.0.0
|IOSerial!F	11
|IOGraphics!F	597
>!ASMBus!C	1.0.18d1
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AActuatorDriver	6400.44
>!AMultitouchDriver	6400.44
>!AInputDeviceSupport	6400.40
>!AHS!BDriver	6000.22
>IO!BHIDDriver	9.0.0
>!UMergeNub	900.4.2
>!ABSDKextStarter	3
|IOSurface	334.0.1
@filesystems.hfs.encodings.kext	1
>!ASyntheticGame!C	10.2.9
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AXsanScheme	3
>!AEFINVRAM	2.1
>!A!ILpssI2C	3.0.60
|IONVMe!F	2.1.0
|IOAHCI!F	301
>!A!ILpssGspi	3.0.60
|IO80211!FLegacy	1200.12.2b1
>corecapture	1.0.4
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
|IOTimeSync!F	1110.13
|IOSkywalk!F	1.0
>mDNSOffloadUserClient	1.0.1b8
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	9.0.0
|IOReport!F	47
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	547
|IOUSBMass!SDriver	232
|IOSCSIBlockCommandsDevice	476
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	476
>!AMobileFileIntegrity	1.0.5
$!AImage4	5.0.0
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
|CoreAnalytics!F	1
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	12.0

**Comment by oldman20** [comment]
Mine not panic, but maybe it doesnt detect cause i using usb ports mapping in Monterey SMBIOS 12.1, now booting Ventura SMBIOS 14.2 changed, maybe need remap usb ports!?

**Comment by 0xFireWolf** [comment]
No symbols? No hardware specification? No detailed description? Closed.
