### ISSUE TITLE
Venture working 0.9.6

### ISSUE THREAD

**Issue by N3kowarrior** [0xFireWolf/RealtekPCIeCardReader#48]
Hi I have the 0.9.6 with friend kext working on mac os Venture. If i update to 0.9.7 kext stops working please mark this (0.9.6) version with this card reader as compatible with mac os Venture.

I copied some data from sd card but i cant demostrate it because it was school work. And I don't have any sd card at home.

![IMG_20231030_184851418](https://github.com/0xFireWolf/RealtekCardReader/assets/118403968/1bbe1ac7-1d84-4ca7-a90d-46a9a7d99e9f)

**Comment by N3kowarrior** [comment]
And i have it in device properties as this:
![IMG_20231030_185141534](https://github.com/0xFireWolf/RealtekCardReader/assets/118403968/9297c3e1-3273-497e-8101-9b45b8d61ea8)

**Comment by 0xFireWolf** [comment]
Cannot reproduce the issue with 0.9.7 on macOS Ventura 13.6. If you believe that this is a bug in 0.9.7, please refer to the FAQ and upload all necessary logs.

Side Note: You can remove those device properties. They are not needed by this driver at all.
