### ISSUE TITLE
statusbar expressCard icon

### ISSUE THREAD

**Issue by cjlhll** [0xFireWolf/RealtekPCIeCardReader#49]
![QQ图片20231104205025](https://github.com/0xFireWolf/RealtekCardReader/assets/26736892/e2f99897-7bf9-4de2-adc7-e271bb3e7e09)
![QQ截图20231104214331](https://github.com/0xFireWolf/RealtekCardReader/assets/26736892/6acc3344-61f4-4cf0-a787-bec0288cb74d)
![QQ截图20231104223904](https://github.com/0xFireWolf/RealtekCardReader/assets/26736892/cfb67d09-8263-48e9-8d3c-0a3d442ae226)
How to delete this icon？

**Comment by 0xFireWolf** [comment]
Google is your friend. 

Your issue is not related to this driver. Please make sure that you don’t inject unnecessary device properties to the SD card reader via the bootloader.
