### ISSUE TITLE
RTS5182 Card Reader is not supported, can it be supported?

### ISSUE THREAD

**Issue by musicclub1563** [0xFireWolf/RealtekPCIeCardReader#51]
RTS5182 Card Reader is not supported, can it be supported?

**Comment by 0xFireWolf** [comment]
RTS5182 is USB based and conforms to the UAS protocol. If it does not work under macOS out of box, you are out of luck.

**Comment by musicclub1563** [comment]
So what should he do

**Comment by musicclub1563** [comment]
So how can he be driven?

**Comment by 0xFireWolf** [comment]
Your card reader, in theory, should work just like a thumb drive. In other words, RTS5182 **is not and will not** be supported by this driver which focuses on custom PCIe- and USB-based card readers. You are welcome to port its drivers from other operating systems.
